/*
 * Casciian - Java Text User Interface
 *
 * Written 2013-2025 by Autumn Lamonte
 *
 * To the extent possible under law, the author(s) have dedicated all
 * copyright and related and neighboring rights to this software to the
 * public domain worldwide. This software is distributed without any
 * warranty.
 *
 * You should have received a copy of the CC0 Public Domain Dedication along
 * with this software. If not, see
 * <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package com.idataconnect.salinas.toolkit;

/**
 * This class encapsulates a user command event.  User commands can be
 * generated by menu actions, keyboard accelerators, and other UI elements.
 * Commands can operate on both the application and individual widgets.
 */
public class TCommand {

    // ------------------------------------------------------------------------
    // Constants --------------------------------------------------------------
    // ------------------------------------------------------------------------

    /**
     * Immediately abort the application (e.g. remote side closed
     * connection).
     */
    public static final int ABORT               = 1;

    /**
     * File open dialog.
     */
    public static final int OPEN                = 2;

    /**
     * Exit application.
     */
    public static final int EXIT                = 3;

    /**
     * Spawn OS shell window.
     */
    public static final int SHELL               = 4;

    /**
     * Cut selected text and copy to the clipboard.
     */
    public static final int CUT                 = 5;

    /**
     * Copy selected text to clipboard.
     */
    public static final int COPY                = 6;

    /**
     * Paste from clipboard.
     */
    public static final int PASTE               = 7;

    /**
     * Clear selected text without copying it to the clipboard.
     */
    public static final int CLEAR               = 8;

    /**
     * Tile windows.
     */
    public static final int TILE                = 9;

    /**
     * Cascade windows.
     */
    public static final int CASCADE             = 10;

    /**
     * Close all windows.
     */
    public static final int CLOSE_ALL           = 11;

    /**
     * Move (move/resize) window.
     */
    public static final int WINDOW_MOVE         = 12;

    /**
     * Zoom (maximize/restore) window.
     */
    public static final int WINDOW_ZOOM         = 13;

    /**
     * Next window (like Alt-TAB).
     */
    public static final int WINDOW_NEXT         = 14;

    /**
     * Previous window (like Shift-Alt-TAB).
     */
    public static final int WINDOW_PREVIOUS     = 15;

    /**
     * Close window.
     */
    public static final int WINDOW_CLOSE        = 16;

    /**
     * Enter help system.
     */
    public static final int HELP                = 20;

    /**
     * Enter first menu.
     */
    public static final int MENU                = 21;

    /**
     * Save file.
     */
    public static final int SAVE                = 30;

    /**
     * Save as file.
     */
    public static final int SAVE_AS             = 31;

    /**
     * Backend disconnected.
     */
    public static final int BACKEND_DISCONNECT  = 100;

    /**
     * Trigger text cursor glint effect.
     */
    public static final int TEXT_CURSOR_GLINT   = 110;

    /**
     * Immediately abort the application (e.g. remote side closed
     * connection).
     */
    public static final TCommand cmAbort        = new TCommand(ABORT);

    /**
     * Exit application.
     */
    public static final TCommand cmExit         = new TCommand(EXIT);

    /**
     * Exit application.
     */
    public static final TCommand cmQuit         = new TCommand(EXIT);

    /**
     * File open dialog.
     */
    public static final TCommand cmOpen         = new TCommand(OPEN);

    /**
     * Spawn OS shell window.
     */
    public static final TCommand cmShell        = new TCommand(SHELL);

    /**
     * Cut selected text and copy to the clipboard.
     */
    public static final TCommand cmCut          = new TCommand(CUT);

    /**
     * Copy selected text to clipboard.
     */
    public static final TCommand cmCopy         = new TCommand(COPY);

    /**
     * Paste from clipboard.
     */
    public static final TCommand cmPaste        = new TCommand(PASTE);

    /**
     * Clear selected text without copying it to the clipboard.
     */
    public static final TCommand cmClear        = new TCommand(CLEAR);

    /**
     * Tile windows.
     */
    public static final TCommand cmTile         = new TCommand(TILE);

    /**
     * Cascade windows.
     */
    public static final TCommand cmCascade      = new TCommand(CASCADE);

    /**
     * Close all windows.
     */
    public static final TCommand cmCloseAll     = new TCommand(CLOSE_ALL);

    /**
     * Move (move/resize) window.
     */
    public static final TCommand cmWindowMove   = new TCommand(WINDOW_MOVE);

    /**
     * Zoom (maximize/restore) window.
     */
    public static final TCommand cmWindowZoom   = new TCommand(WINDOW_ZOOM);

    /**
     * Next window (like Alt-TAB).
     */
    public static final TCommand cmWindowNext   = new TCommand(WINDOW_NEXT);

    /**
     * Previous window (like Shift-Alt-TAB).
     */
    public static final TCommand cmWindowPrevious = new TCommand(WINDOW_PREVIOUS);

    /**
     * Close window.
     */
    public static final TCommand cmWindowClose  = new TCommand(WINDOW_CLOSE);

    /**
     * Enter help system.
     */
    public static final TCommand cmHelp         = new TCommand(HELP);

    /**
     * Save file.
     */
    public static final TCommand cmSave         = new TCommand(SAVE);

    /**
     * Save as file.
     */
    public static final TCommand cmSaveAs       = new TCommand(SAVE_AS);

    /**
     * Enter first menu.
     */
    public static final TCommand cmMenu         = new TCommand(MENU);

    /**
     * Backend disconnected.
     */
    public static final TCommand cmBackendDisconnect    = new TCommand(BACKEND_DISCONNECT);

    /**
     * Trigger text cursor glint effect.
     */
    public static final TCommand cmTextCursorGlint      = new TCommand(TEXT_CURSOR_GLINT);

    // ------------------------------------------------------------------------
    // Variables --------------------------------------------------------------
    // ------------------------------------------------------------------------

    /**
     * Type of command, one of EXIT, CASCADE, etc.
     */
    private int type;

    // ------------------------------------------------------------------------
    // Constructors -----------------------------------------------------------
    // ------------------------------------------------------------------------

    /**
     * Public constructor.
     *
     * @param type the Type of command, one of EXIT, CASCADE, etc.
     */
    public TCommand(final int type) {
        this.type = type;
    }

    // ------------------------------------------------------------------------
    // TCommand ---------------------------------------------------------------
    // ------------------------------------------------------------------------

    /**
     * Make human-readable description of this TCommand.
     *
     * @return displayable String
     */
    @Override
    public final String toString() {
        return String.format("%s", type);
    }

    /**
     * Comparison check.  All fields must match to return true.
     *
     * @param rhs another TCommand instance
     * @return true if all fields are equal
     */
    @Override
    public final boolean equals(final Object rhs) {
        if (!(rhs instanceof TCommand)) {
            return false;
        }

        TCommand that = (TCommand) rhs;
        return (type == that.type);
    }

    /**
     * Hashcode uses all fields in equals().
     *
     * @return the hash
     */
    @Override
    public int hashCode() {
        return type;
    }

}
