usageString=USAGE: java -cp com.idataconnect.salinas.toolkit.jar com.idataconnect.salinas.toolkit.demos.Demo8 port
newConnection=New connection: {0}
username=\ \ \ username: {0}
language=\ \ \ language: {0}
terminal=\ \ \ terminal: {0}
exitMain=Main thread is exiting...
