/*
 * Casciian - Java Text User Interface
 *
 * Written 2013-2025 by Autumn Lamonte
 *
 * To the extent possible under law, the author(s) have dedicated all
 * copyright and related and neighboring rights to this software to the
 * public domain worldwide. This software is distributed without any
 * warranty.
 *
 * You should have received a copy of the CC0 Public Domain Dedication along
 * with this software. If not, see
 * <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package com.idataconnect.salinas.toolkit.event;

import com.idataconnect.salinas.toolkit.TCommand;
import com.idataconnect.salinas.toolkit.backend.Backend;

/**
 * This class encapsulates a user command event.  User commands can be
 * generated by menu actions, keyboard accelerators, and other UI elements.
 * Commands can operate on both the application and individual widgets.
 */
public class TCommandEvent extends TInputEvent {

    // ------------------------------------------------------------------------
    // Variables --------------------------------------------------------------
    // ------------------------------------------------------------------------

    /**
     * Command dispatched.
     */
    private TCommand cmd;

    // ------------------------------------------------------------------------
    // Constructors -----------------------------------------------------------
    // ------------------------------------------------------------------------

    /**
     * Public contructor.
     *
     * @param backend the backend that generated this event
     * @param cmd the TCommand dispatched
     */
    public TCommandEvent(final Backend backend, final TCommand cmd) {
        super(backend);

        this.cmd = cmd;
    }

    // ------------------------------------------------------------------------
    // TInputEvent ------------------------------------------------------------
    // ------------------------------------------------------------------------

    /**
     * Comparison check.  All fields must match to return true.
     *
     * @param rhs another TCommandEvent or TCommand instance
     * @return true if all fields are equal
     */
    @Override
    public boolean equals(final Object rhs) {
        if (!(rhs instanceof TCommandEvent)
            && !(rhs instanceof TCommand)
        ) {
            return false;
        }

        if (rhs instanceof TCommandEvent) {
            TCommandEvent that = (TCommandEvent) rhs;
            return (cmd.equals(that.cmd)
                && (getTime().equals(that.getTime())));
        }

        TCommand that = (TCommand) rhs;
        return (cmd.equals(that));
    }

    /**
     * Hashcode uses all fields in equals().
     *
     * @return the hash
     */
    @Override
    public int hashCode() {
        int A = 13;
        int B = 23;
        int hash = A;
        hash = (B * hash) + getTime().hashCode();
        hash = (B * hash) + cmd.hashCode();
        return hash;
    }

    /**
     * Make human-readable description of this TCommandEvent.
     *
     * @return displayable String
     */
    @Override
    public String toString() {
        return String.format("CommandEvent: %s", cmd.toString());
    }

    // ------------------------------------------------------------------------
    // TCommandEvent ----------------------------------------------------------
    // ------------------------------------------------------------------------

    /**
     * Get TCommand.
     *
     * @return the TCommand
     */
    public TCommand getCmd() {
        return cmd;
    }

}
